# Generated by Django 3.0.3 on 2020-05-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaaS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called', models.CharField(max_length=100)),
                ('calledDisplay', models.CharField(max_length=100)),
                ('templateID', models.CharField(max_length=100)),
                ('params', models.CharField(max_length=500)),
                ('playTimes', models.IntegerField(max_length=4)),
                ('playDelay', models.IntegerField(max_length=10)),
                ('data', models.TextField()),
            ],
        ),
    ]
