# Generated by Django 3.0.6 on 2020-05-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpaasapi', '0002_auto_20200511_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('api_name', models.CharField(max_length=20)),
                ('api_product', models.IntegerField()),
                ('api_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='api_param',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('api_id', models.IntegerField()),
                ('param', models.CharField(max_length=50)),
                ('f_param', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
